# Generated by Django 5.2.5 on 2024-01-01 00:01

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pagamento'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
    ]

    operations = [
    ]
